apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-mlops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti-mlops
  template:
    metadata:
      labels:
        app: olivetti-mlops
    spec:
      containers:
      - name: olivetti-mlops-container
        image: vritant1003/olivetti-mlops:latest
        ports:
        - containerPort: 5001